### ISSUE TITLE
The DPoP proof JWT cannot be parsed

### ISSUE THREAD

**Issue by nyklav** [okta/okta-sdk-dotnet#758]
### Describe the bug?

I have an `API Services` application configured to use a `Public Key / Private Key`.

According to the [documentation,](https://github.com/okta/okta-sdk-dotnet?tab=readme-ov-file#oauth-20) DPoP should have been handled automatically, but it threw the error.

Error calling GetBearerToken: 
```json
{
  "error": "invalid_dpop_proof",
  "error_description": "DPoP proof JWT cannot be parsed."
}
```

### What is expected to happen?

DPoP should be handled automatically.

### What is the actual behavior?

The error `“DPoP proof JWT cannot be parsed”` occurs.

### Reproduction Steps?

Try to get an access token using a `Private Key` with the `“Require Demonstrating Proof of Possession (DPoP)”` option enabled

### .NET Version

8.0.403

### SDK Version

9.0.0

### OS version

BuildNumber | Caption                    | OSArchitecture | Version
---------------|-----------------------|------------------|--------------------
19045            | Microsoft Windows  | 10 Pro  64-bit   | 10.0.19045

**Comment by bryanapellanes-okta** [comment]
@nyklav Thanks for bringing this to our attention and I apologize for the delayed response.  I've entered an internal issue for tracking and prioritization: OKTA-832982

**Comment by aniket-okta** [comment]
Issue is fixed and will be released with the v9.2.2

**Comment by jzebedee** [comment]
This is not fixed and still fails DPoP validation as of v9.2.3

**Comment by derekfinlinson** [comment]
Still having this issue as well with v9.2.3
