### ISSUE TITLE
Problem with GetConfigurationOrDefault Method in Okta

### ISSUE THREAD

**Issue by pancholi24-usi** [okta/okta-sdk-dotnet#766]
### Describe the bug?

I’m experiencing a similar issue to what is discussed in
(https://devforum.okta.com/t/getconfigurationordefault-throwing-object-reference-not-set-to-an-instance-of-an-object/28968).

The **Okta.AspNetCore** version that I am on is **4.6.1**

Here’s the piece of code I have to get user details. While I do receive the user details, I also encounter the above exception, which seems to bypass but still gives me the result.

var oktaConfig = new Configuration()
{
Token = configuration[“OktaToken”],
OktaDomain = configuration[“OktaDomain”],
};

UserApi = new UserApi(oktaConfig);
var user = UserApi.GetUserAsync(“[test.user@test.com](mailto:test.user@test.com)”).Result;
var name = user.Profile.DisplayName;

Has anyone found a solution for this issue? Any guidance would be greatly appreciated!

### What is expected to happen?

Call the OKTA API without any error

### What is the actual behavior?

When I run the solution, Visual Studio breaks at the GetAllProperties() method inside ConfigurationBinder.cs because type is null. I can continue through the errors and it will eventually run, however I’m not sure if the results are accurate.

System.NullReferenceException
HResult=0x80004003
Message=Object reference not set to an instance of an object.
Source=Microsoft.Extensions.Configuration.Binder
StackTrace:
at Microsoft.Extensions.Configuration.ConfigurationBinder.GetAllProperties(Type type) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs:line 654

Furthermore, the calling line in the OKTA SDK is Okta.Sdk.Client.Configuration.cs, Line 594, GetConfigurationOrDefault().
That line reads:
configurationBuilder.Build().GetSection("okta").GetSection("client") .Bind(configuration);

The line that calls that is line 39 in Okta.Sdk.Api.UserApi():
configuration = Okta.Sdk.Client.Configuration.GetConfigurationOrDefault(configuration);

### Reproduction Steps?

When I run the solution, Visual Studio breaks at the GetAllProperties() method inside ConfigurationBinder.cs because type is null. I can continue through the errors and it will eventually run, however I’m not sure if the results are accurate.

System.NullReferenceException
HResult=0x80004003
Message=Object reference not set to an instance of an object.
Source=Microsoft.Extensions.Configuration.Binder
StackTrace:
at Microsoft.Extensions.Configuration.ConfigurationBinder.GetAllProperties(Type type) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs:line 654

Furthermore, the calling line in the OKTA SDK is Okta.Sdk.Client.Configuration.cs, Line 594, GetConfigurationOrDefault().
That line reads:
configurationBuilder.Build().GetSection("okta").GetSection("client") .Bind(configuration);

The line that calls that is line 39 in Okta.Sdk.Api.UserApi():
configuration = Okta.Sdk.Client.Configuration.GetConfigurationOrDefault(configuration);

### .NET Version

.net 6.0

### SDK Version

Okta.AspNetCore version is 4.6.1
Okta.Sdk version tried 8.0.1 and 9.0.3(latest) both have same issue
Okta.Auth.Sdk version is 2.0.5

**Comment by bryanapellanes-okta** [comment]
@pancholi24-usi Thanks for reporting this!  I've entered an internal issue for tracking and prioritization. OKTA-852181

**Comment by pancholi24-usi** [comment]
Thanks for responding on our issue request. Is there any ETA for this and priority defined ? We are currently in holding pattern due to this so want to know.

**Comment by pancholi24-usi** [comment]
Is there any ETA ? we are holding up on changes due to this bug. Any alternative solution please ?

**Comment by aniket-okta** [comment]
@pancholi24-usi We're currently working on this issue as a top priority. Should be resolved by next week.

**Comment by aniket-okta** [comment]
@pancholi24-usi I am not able to reproduce this issue. Could you please confirm if you're still able to reproduce this problem in the latest version which is 9.1.1? Also, if you're receiving results from the API it should be functioning correctly as the error appears to be internal to configuration resolution within the Microsoft's code that you referenced.

**Comment by pancholi24-usi** [comment]
Hi @aniket-okta we just tried the latest version 9.1.1 and still failing. We are using the same code and still we see object reference error. Please see attached screenshots.

![Image](https://github.com/user-attachments/assets/c94c7a56-6aaa-4c1f-ac50-0e7e88d82f60)

![Image](https://github.com/user-attachments/assets/8fe99e00-b6e0-466a-8733-07f06efa7eba)

![Image](https://github.com/user-attachments/assets/63e63212-431f-46f9-96d5-78e25c1de7c9)

![Image](https://github.com/user-attachments/assets/9b6db979-7ac4-4f65-82e5-3c69b25fe751)

Please let us know if you need any more info. We still able to reproduce it.

**Comment by bobby-bridges-wex** [comment]
I'm having this same issue with UserApi using version 9.1.0. It breaks as soon as UserApi is instantiated 

![Image](https://github.com/user-attachments/assets/3fb0533a-6979-40fd-bb13-3dd07f11e560)

**Comment by bryanapellanes-okta** [comment]
@pancholi24-usi In our continued review of this issue, I notice in your screen shot that you are debugging code that is in `Microsoft.Extensions.Configuration`, further, in the problem description you state `"I can continue through the errors and it will eventually run, however I’m not sure if the results are accurate."`.  You would see an error from the Okta SDK or the Okta API if API calls failed.  It is possible that the configuration system is attempting to read configuration structure that is not present in your configuration file.  Because not all configuration sections are necessary for all uses of the SDK, the exception is handled, code execution successfully proceeds, and you are able to make API calls without issue.  This problem occurs in `Microsoft.Extensions.Configuration` and because your code continues execution, this shouldn't be a concern.  

However, we can review the configuration related code to determine what changes we can make to prevent the exception. We'll need your help to do this; without including sensitive information, please share the content and structure of your configuration file located at ~/.okta/okta.yaml.  Also, it would be helpful to know in what way you have included the `Microsoft.Extensions.Configuration` code in your project to help us reproduce the behavior on our side.  Did you include the source or did you use a decompiler included in your IDE (perhaps by stepping through or using "go to implementation" or similar)? Finally, please let us know what IDE you are using.

To summarize, please provide the following:
- content and structure of ~/.otka/okta.yaml, excluding sensitive information
- description of project structure including how the `Microsoft.Extensions.Configuration` code is referenced in your project
- IDE name and version

We appreciate your help as we investigate further, and thanks for using Okta!

**Comment by pancholi24-usi** [comment]
Hi @bryanapellanes-okta 

The setup is quite simple. Here’s my Okta Services file which is nothing but a bunch of Okta API calls. 

Below is my code snippet to call this call on Startup.cs

    public void ConfigureServices(IServiceCollection services)
    {
        if (_webHostingEnvironment.IsDevelopment())
        {
            AppDomain.CurrentDomain.SetData("DataDirectory",
                Path.Combine(_webHostingEnvironment.ContentRootPath, "App_Data"));

            services.Configure<SchedulerOptions>(options => options.Enabled = false);
        }
services.AddTransient<IOktaServices, OktaServices>();
    }

   var oktaConfig = new Configuration()
   {
       Token = configuration["OktaToken"],
       OktaDomain = configuration["OktaDomain"]
   };
   UserApi = new UserApi(oktaConfig);

 
The exception occurs when the code reaches new UserApi(oktaConfig);

I know for a fact that OktaConfig is populated correctly but there’s something that the UserAPI is expecting which is why it is throwing exception.

I can continue once the exception occurs but the problem is it breaks my code which is why we raised this issue.

In terms of setup ,just add the okta sdk package at your end with the user’s api call as below

   var oktaConfig = new Configuration()
   {
       Token = configuration["OktaToken"],
       OktaDomain = configuration["OktaDomain"]
   };
   UserApi = new UserApi(oktaConfig); 

& you’ll get the exception which breaks the code.

Sharing the Quick watch for oktaConfig that I have. I do have the token & domain which I believe is required for fetching UserAPi .Anything else that is missing let me know & I can try that & update

![Image](https://github.com/user-attachments/assets/3a4ccf5c-bd0d-4a08-9b0a-1db241307854)

![Image](https://github.com/user-attachments/assets/7d2ed0e4-802c-4632-aa75-76d6ee3d8b6d)

**Comment by bryanapellanes-okta** [comment]
@pancholi24-usi It looks like you're working inside an Asp.Net project.  Please confirm which project template your project is based on so that I can try to reproduce the behavior.  Also, please confirm what operating system you're on.  Thanks!

**Comment by pancholi24-usi** [comment]
@bryanapellanes-okta Here are the details.
.NET version **6.0** (upgraded from .net4.8 to .net6.0)
OS: **Windows**
Project Template: any template but currently using **.NET Core**. 

You can create any .NET Core sample application and can copy my code below to your Porgram.cs class.


```
var builder = WebApplication.CreateBuilder(args); 

// Add services to the container.
builder.Services.AddControllersWithViews();
builder.Services.AddTransient<IOktaServices, OktaServices>();

var app = builder.Build(); 

var oktaService = app.Services.GetRequiredService<IOktaServices>();
var result = oktaService.UserApi;
 
// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseAuthorization();
app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");
app.Run();
```

**Comment by pancholi24-usi** [comment]
Here is my **OktaService** class code

```
using Okta.Auth.Sdk;
using Okta.Sdk.Abstractions.Configuration;
using Okta.Sdk.Api;
using Okta.Sdk.Client;

namespace myproject.setup.Business
{
    public interface IOktaServices
    {
        public IUserApi? UserApi { get; }
    }

    public class OktaServices : IOktaServices
    {
        public IUserApi? UserApi { get; }

        public OktaServices(IConfiguration configuration)
        {
            var oktaConfig = new Configuration()
            {
                Token = configuration["OktaToken"],
                OktaDomain = configuration["OktaDomain"]
            };
            UserApi = new UserApi(oktaConfig);
            var user = UserApi.GetUserAsync("test.user@test.com").Result;
            var name = user.Profile.DisplayName;
        }
    }
}
```

**Comment by bryanapellanes-okta** [comment]
@pancholi24-usi Thank you for the additional information.  I've created a project and copied the code you provided verbatim into the project and I am still unable to reproduce the behavior described.  

May I have you share a branch with a project that reproduces this behavior?  Be careful not to expose sensitive information.

Additionally, you might also try unchecking "Common Language Runtime Exceptions" from the Visual Studio exception settings found in Debug > Windows > Exception Settings.

**Comment by bobby-bridges-wex** [comment]
@bryanapellanes-okta this exception is originating from the okta sdk during initialization. I'm not sure turning off exceptions is the right approach here. 

![Image](https://github.com/user-attachments/assets/2e54b4ee-2a5c-4fe8-988a-041ada81aa78)

**Comment by FarhinShaikh28** [comment]
@bryanapellanes-okta  I’ve tried unchecking **"Common Language Runtime Exceptions,"** and while it stops the debugger from breaking on those exceptions, it's not really a solution. It ends up suppressing other critical exceptions I need to see, which can lead to missing important bugs.

I’d appreciate any other approach or fix that addresses the root cause without affecting other exceptions. Would love to hear what others have done in a similar situation!

**Comment by bryanapellanes-okta** [comment]
I'm doing some setup to be able to reproduce the behavior and I'll follow up when I have additional information.

**Comment by bryanapellanes-okta** [comment]
@bobby-bridges-wex  This exception is clearly coming from `Microsoft.Extensions.ConfigurationBinder` as shown in the image you shared:

![Image](https://github.com/user-attachments/assets/12ab8de6-2a08-4785-9986-a5c043323971)

@pancholi24-usi Please confirm what version of the Microsoft.Extensions.Configuration package you have referenced. 

Additionally, may I have you place a breakpoint on line 36 of your OktaServices file and run the application with the following setting unchecked: "Common Language Runtime Exceptions" from the Visual Studio exception settings found in Debug > Windows > Exception Settings 

Alternatively, if you prefer not to tell the IDE not to stop code execution on all exceptions, after the exception is hit and the code execution stops, please step through the code until either the process exits with a non 0 code or the exception is handled and code execution continues.

![Image](https://github.com/user-attachments/assets/04ad855e-af32-443d-8862-7ac3a0e619ff)

**Comment by bryanapellanes-okta** [comment]
I continue to be unable to reproduce the behavior described.

**Comment by bryanapellanes-okta** [comment]
@FarhinShaikh28 I invite you to do what I suggest in my comment here: https://github.com/okta/okta-sdk-dotnet/issues/766#issuecomment-2682876429

Please tell me what results you get.

**Comment by FarhinShaikh28** [comment]
@bryanapellanes-okta  I get the below exception.

![Image](https://github.com/user-attachments/assets/16455725-e384-46cc-a123-60805a362586)
Once the application crashes, it also returns the API response containing the requested user information. In short, the exception breaks my code and then returns the result.

**Comment by bryanapellanes-okta** [comment]
@FarhinShaikh28 

> Once the application crashes, it also returns the API response containing the requested user information. In short, the exception breaks my code and then returns the result.

This statement is self contradictory, either the application crashes and the process exits or code execution continues.  The fact that you are getting user information means that code execution continued which implies the exception was handled prior to control being returned to the line that retrieved user information.  Does the debug session continue or do you need to press the stop button?

**Comment by bryanapellanes-okta** [comment]
@pancholi24-usi Please advise what IDE and version you are using.  At this point I'm trying to determine why you have the source for `Microsoft.Extensions.Configuration` in your project for the debugger to stop at what appears to be handled a handled exception, based on the statements you and FarhinShaikh have made.

**Comment by FarhinShaikh28** [comment]
@bryanapellanes-okta  we are using Visual Studio 2022. Please see attached video.

https://github.com/user-attachments/assets/7fb1c184-1ade-4c59-99db-4a08f89620f6

**Comment by bryanapellanes-okta** [comment]
> [@bryanapellanes-okta](https://github.com/bryanapellanes-okta) we are using Visual Studio 2022. Please see attached video.
> 
>  Okta.mp4

This video illustrates that the exception is being handled and code execution continues without issue.

**Comment by FarhinShaikh28** [comment]
@bryanapellanes-okta, I’m not sure why you would classify this labeling as a user error. I have provided a video outlining the issue. There are no empty configurations that would cause the null exception, because if that were the case, the response would not be returned after the exception is thrown. I understand it may sound contradictory, but the video demonstrates that the code is breaking. I would really appreciate it if you could provide a valid response before closing the issue. If needed, I can share the source code as well.

**Comment by pancholi24-usi** [comment]
Hi @bryanapellanes-okta we expect the reason and explanation for the exception before you mark the ticket with user-error, closed and completed. Please let us know we can schedule a call for the details. Thanks.
